### PR TITLE
Added V4 Operations to Basho Bench Driver

### PR DESCRIPTION
**Pull request by windkit**
### Brief Description
Added V4 Support to Basho Bench driver

### Related Pull Requests
 - https://github.com/leo-project/leo_gateway/pull/24
 - https://github.com/leo-project/leo_s3_libs/pull/2
 - https://github.com/leo-project/leo_commons/pull/3

### CODE REVIEW

**Comment by mocchira** [comment]
@windkit 
As I created a new branch for 1.4, Please PR to 1.4.

**Comment by mocchira** [comment]
@windkit I have some comments so please wait PR for a while.

**Comment by windkit** [comment]
Oops... Anyway, discussion would move to https://github.com/leo-project/basho_bench/pull/1 from now on

**Comment by mocchira** [comment]
As we have own basho_bench, 
we should not copy&paste code but make dependencies to leo_s3_libs, leo_commons and ninenines/cowlib using rebar.config.

**Comment by mocchira** [comment]
Other part LGTM.

**Comment by windkit** [comment]
Thanks for fixing the dependency

**Pull request merged**
